# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'sinatra'
gem 'rails'
gem 'capybara'
gem 'sqlite3', '~> 1.3.6'
gem 'nokogiri'
gem 'activerecord', :require => "active_record"
gem 'rake'
gem 'pry'
gem 'sinatra-activerecord'
gem 'require_all'
gem 'rack'
gem 'bcrypt'
gem 'tux'